export const SET_REGISTRATION_VALIDATION_MESSAGES = "SET_REGISTRATION_VALIDATION_MESSAGES";
export const SET_REGISTRATION_SUCCESS = "SET_REGISTRATION_SUCCESS";

export const SET_LOGIN_ERROR_MESSAGES = "SET_LOGIN_ERROR_MESSAGES";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";

export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_DATA_ERRORS = "SET_USER_DATA_ERRORS";

export const LOGOUT = "LOGOUT";